[etcd]
etcd01 ansible_host=10.168.2.108 etcd_name=etcd01
etcd02 ansible_host=10.168.2.109 etcd_name=etcd02
etcd03 ansible_host=10.168.2.110 etcd_name=etcd03

[etcd:vars]
ansible_user=root
ansible_become=true
etcd_version=3.5.16
etcd_data_dir=/var/lib/etcd
etcd_client_port=2379
etcd_peer_port=2380
etcd_initial_cluster_token=etcd-cluster-1
etcd_initial_cluster_state=new
etcd_initial_cluster=etcd01=http://10.168.2.108:2380,etcd02=http://10.168.2.109:2380,etcd03=http://10.168.2.110:2380

