[kubernetes_nodes]
# Replace these examples with the actual Ubuntu 24.04 node addresses.
# Use ansible_user/ansible_host variables here when SSH differs from the host address.
# node01 ansible_host=10.168.2.110 ansible_user=ubuntu
# node02 ansible_host=10.168.2.111 ansible_user=ubuntu
k8s-master-01 ansible_host=10.168.2.100 ansible_user=root
k8s-master-02 ansible_host=10.168.2.101 ansible_user=root
k8s-master-03 ansible_host=10.168.2.102 ansible_user=root
k8s-node-01 ansible_host=10.168.2.103 ansible_user=root
k8s-node-02 ansible_host=10.168.2.104 ansible_user=root
k8s-node-03 ansible_host=10.168.2.105 ansible_user=root
k8s-node-04 ansible_host=10.168.2.106 ansible_user=root
k8s-node-05 ansible_host=10.168.2.107 ansible_user=root


[kubernetes_nodes:vars]
ansible_become=true
