
[keepalive_haproxy]
lb01 ansible_host=10.168.2.100 vrrp_priority=100
lb02 ansible_host=10.168.2.101 vrrp_priority=90 
lb03 ansible_host=10.168.2.102 vrrp_priority=80

[keepalive_haproxy:vars]
ansible_user=root
ansible_become=true
vrrp_vip=10.168.2.188
vrrp_interface=ens18
vrrp_router_id=51
vrrp_auth_pass=HaPass12
haproxy_frontend_port=80
haproxy_stats_port=8404
